### ISSUE TITLE
人工反向工程数据集

### ISSUE THREAD

**Issue by liyongsea** [liyongsea/parallel_corpus_mnbvc#19]
- human annotated dataset (17)
- synthetic data

**Comment by Wzixiao** [comment]
---------------------------------------------------
| |  precision|    recall|  f1-score  | support|
------------------------------------------------
|       False    |   0.95  |      0.97     |   0.96   |    24100|  
|        True    |     0.89   |     0.82   |     0.86 |       7109|  
| | | | |
|    accuracy        |                  |    0.94   |    31209|  
|   macro avg   |      0.92    |    0.90    |    0.91   |    31209|  
| weighted avg    |     0.94    |    0.94   |     0.94   |    31209|  
------------------------------------------------

**Comment by Wzixiao** [comment]
一个从https://www.gutenberg.org/下载的书籍制作的反向数据库
- raw_text: 下载的元文本，经过删除空的行处理后的字符串
- output_text: 下载的元文本，将空的行变成\n处理后的字符串

数据集地址:https://huggingface.co/datasets/ranWang/books_paragraph

**Comment by Wzixiao** [comment]
以下是制作的第一版手动微调的dataset的其中10行
![20230614213939-1346x446](https://github.com/liyongsea/parallel_corpus_mnbvc/assets/90966139/a8cd5a6f-f6cd-48b8-b85f-07dc43fb4eb6)
