### ISSUE TITLE
[Alignment] Propose alignment algorithm draft

### ISSUE THREAD

**Issue by liyongsea** [liyongsea/parallel_corpus_mnbvc#3]
Given an UN article in 6 language, propose a method to align paragraphs/sentences.
some ideas:
- translate a zh article in en
- measure paragraph similarity (jaccard similarity, minhash)

One can inspire from 
- https://conferences.unite.un.org/uncorpus/Content/Doc/un.pdf
- https://huggingface.co/datasets/un_pc

**Comment by voidf** [comment]
一些发现：
- 拿到的文本连续一行的都是相关的
- 换段和回车符是相关的，有的回车符有换段意义，有的没有 （这个规则可能比较重要，将换行符和其他空格字符区别开来）
- 句号很重要，可以作为分段依据之一
- 其他标点符号也很重要，行尾的符号除句号外，可以作为删除换行的条件
- 连续出现的whitespace类型字符是没有意义的，所以可以换成一个
- 连续出现的相同标点符号可能是没有意义的，但是目录里的对齐符是为了保留格式
- 中文不同于其它5国语言，不会用空格隔开词语，所以需要一种方法删掉词语中多出来的空格
- 对于每一页，文章里都会出现模式相似的冗余噪声信息，比如页码，日期
- 这些文章数据里频繁出现有序列表，可以对这个特点写条件把那些长列表都提出来
- 英文中会出现i、ii、iii的罗马数字标号，且有可能有类似OCR扫描的错误，如iii打成Hi，需要一种计算编辑距离的机制

规则：
- 根据文件做前（后）向临近词频分析，对于每个单词，每次提取出仅包括本语言文字的连续的一行（见随后的正则），扫描紧随其后的单词统计这种临近词对个数，删回车时根据删除后临近两个词在全文中的出现频率是否大于某个阈值来决定
- 由于PDF排版性质，每行有最大字符限制，可以根据行的字数来决定这个换行要不要删（必要条件）
- 以逗号顿号反括号结尾的换行要删
- 以句号结尾的换行不删

工作方向：
1. 先做英语的段落。
2. 把其它语言的段落映射到英语去。

**Comment by voidf** [comment]
符号表：
```python
regular_exp = {
    # 除中文外，句子中都含空格
    'ar': re.compile(r'[\u0600-\u06ff ]+'),
    'zh': re.compile(r'[\u3006\u3007\u4e00-\u9fff\u3400-\u4dbf\U00020000-\U0002a6df\U0002a700-\U0002ebef\U00030000-\U0003134f]+'),
    'fr': re.compile(r'[a-zA-ZÀ-Ÿ ]+'),
    'es': re.compile(r'[a-zA-ZáéíóúñÁÉÍÓÚÑüÜ ]+'),
    'ru': re.compile(r'[А-я,Ё,ё ]+'),
    'en': re.compile(r'[A-Za-z ]+'),
}

period = {
    'zh': '。',
    'ar': '،',
    # 以下都是半角ascii句点
    'en': '.',
    'es': '.',
    'fr': '.',
    'ru': '.',
}

punctuations = {
    'ar': {
        '،': '.',  # full stop
        '.': '.',  # full stop
        '!': '!',  # exclamation mark
        '؟': '?',  # question mark
        '،': ',',  # comma
        '؛': ';',  # semicolon
        ':': ':',  # colon
        '“': '"',  # left quotation marks
        '”': '"',  # right quotation marks
    },
    'zh': {
        '，': ',',
        '。': '.',
        '：': ':',
        '？': '?',
        '！': '!',
        '；': ';',
        '“': '"',
        '”': '"',
        '（': '(',
        '）': ')',
    },
}

all_punctuation_set = set(string.punctuation)
for k, v in punctuations.items():
    all_punctuation_set.update(v.keys())

digits = {
    'ar': {
        '٠': 0,
        '١': 1,
        '٢': 2,
        '٣': 3,
        '٤': 4,
        '٥': 5,
        '٦': 6,
        '٧': 7,
        '٨': 8,
        '٩': 9,
    },
    'zh': {
        '零': 0,
        '一': 1,
        '二': 2,
        '三': 3,
        '四': 4,
        '五': 5,
        '六': 6,
        '七': 7,
        '八': 8,
        '九': 9,
        '十': 10,
    }
}
```

**Comment by voidf** [comment]
含______的页有注释块，含.......比较多的页为目录页

**Comment by liyongsea** [comment]
文章分段和对齐，这一部分由夜夜全权负责。我有以下几个要求：
1）做出来的方案要符合现实。目前没有大算力加持的情况下，最好做相对简单的模型。能把12万文档在一周内跑通最好
2）至少对其以后做一个小规模的evaluation。自己做一个小数据集也可以，用原来的联合国数据集也可以

**Comment by voidf** [comment]
bertalign的东西：
- LaBSE模型：生成语言无关的句子向量，默认768的维度，但这是面向句子做的模型
- overlaps，代码里把临近若干行（可以修改max_align）合成一句话，做成一种长(max_align-1)*len(sent)的overlaps
- vecs是一个(num_overlap, len(sent), 768)维度的向量，第0维是原句，第1维是overlaps为2，以此类推
- 超过1e4个字符的overlap，会被截断

**Comment by voidf** [comment]
### 5月7号进度更新

- 重写了去除分页页眉页脚的规则，不依赖正则，而是使用词频统计，对任意语言效果良好
- 中/英成段接入bertalign，会根据成段粒度决定消耗的算力，2950篇文章（5种语言，ar除外）对齐需要约8~9个的卡时（3090），瓶颈主要在显卡消耗上
- 和多模态的成员对接，上游任务的pdf提取文字如果条件允许，可以使用pdfalto加上手写规则来获得更干净的文本
- 发现了一些其它可能有用的工具：difflib（Python自带库，效率不高）、string2string（第三方库，未做尝试）
- 发现了一些可能有用的资料：https://medium.com/@yashj302/spell-check-and-correction-nlp-python-f6a000e3709d

#### 一些问题

- 目前的方法显卡算力要求仍比较大
- pdf语料中有一定成分的表格，这些数据我们几乎无法处理，正在重新爬取网站中的元信息，用来过滤这些语料，一个例子：https://digitallibrary.un.org/record/733525
- 35个G的数据用的是pypdf2导出，现在更换pypdfium2重新导出，但是部分文章仍然存在乱码问题，俄语乱码的例子：https://digitallibrary.un.org/record/508762
- 中文分句：没有找到好用的中文分句轮子，目前的分句主要依靠标点符号。语料中有一定成分的中文会丢失标点符号，这会直接导致我们无法分句，例子：https://digitallibrary.un.org/record/432027
- 英文分句：使用nltk.sent_tokenize()，它会把形如1.的数字标号单独分成一句，比较影响对齐效果
- 中英成段对齐效果不非常好，例外很多，现阶段主要依靠段首的标号进行处理
- 阿拉伯语我们还是没有一个比较好的处理办法

#### 其它方向

- 抛弃规则，使用本地机翻（Helsinki-NLP/opus-mt-zh-en）+局部匹配（string2string或difflib）的方法同时做成段和对齐
- - 已知的问题1：机翻有长度限制（比较重要的问题），且有可能出现局部文字无限循环（情况不多）
- - 已知的问题2：局部匹配算法的CPU消耗很大（平方或者立方级别）
- 为目前的规则调参
- - 需要一种能够量化规则产出的成段文本的好坏的办法，我没有idea，需要帮助
- - 目前的规则有很多超参数，我无法用肉眼一一确定该如何调整，能不能用机器学习的办法（例如梯度下降）自动完成调参工作，我没有idea，需要帮助
- - 需要做一定的测试数据
- 只做目录对齐
- - 如果存在目录，只对目录做对齐，不尝试用进一步的办法做更细粒度的对齐，或者把这些工作放到以后
- 上游数据的优化
- - 使用其它工具进行文字提取，但多模态小组似乎只处理中/英，而且目前来看他们的办法算力开销也不小（10页文本2s）

**Comment by voidf** [comment]
### 需要摇人的任务
- 机翻方向，现在只是有个想法，还没人动手
- 文本内部噪声，如注解，需要一定的清洗手段（这些会对现有的一些规则产生比较严重的影响），需要有人来调研Text correction
- 多进程/分布式地分发任务，现在的实验环境只是本人的电脑用单进程跑，如果需要把任务发给集群去做，还需要一些有经验的人来写并发系统
- 调研中文（或其它语言）的成**句**轮子
- 调研其它对齐办法（和轮子）
- 需要人来手动对齐一些pdf，并且需要商量一个量化对齐好坏的办法，商量一个人工对齐如何做成机器表示的办法
- 上游数据来源的优化（这方面要不要做待定）

**Comment by liyongsea** [comment]
- Use chatgpt to do sentence segmentation (??$)
- chatgpt to generate annotation, then train a bert

**Comment by liyongsea** [comment]
- 做测试数据集
    1. Chatgpt合成
    2. 人工反向生成
- 自己训练一个小模型
- 多模型对比
