### ISSUE TITLE
中英文对齐的探索

### ISSUE THREAD

**Issue by liyongsea** [liyongsea/parallel_corpus_mnbvc#37]

**Comment by voidf** [comment]
我的方案：对英文成好的段落跑opus_mt的机翻，翻成中文，然后按中文每个字进行lcs对齐，使用和gpt生产成段类似的方法来得到中-英对齐的目的。

**Comment by Wzixiao** [comment]
在测试的方案1:
- 对中文的每一行跑opus_mt的机翻，翻成英文
- 对英文的每一个段落提取词向量
- 在提取英文词向量的途中，逐步遍历翻译好的中文，将当前round中文行加上当前round之前的所有中文（不包含上一次匹配英文的结果）提取词向量
- 对于每一个英文段落：匹配上一步的中文的词向量的寻找最高值的相似度，并检测最高值处的结尾是否为句号，根据检测结果返回对应的中文段落

**Comment by Wzixiao** [comment]
全部思路放到以下wiki
https://wiki.mnbvc.org/doku.php/%E5%AF%B9%E9%BD%90%E7%AE%97%E6%B3%95#%E5%9F%BA%E4%BA%8E%E6%9C%80%E9%95%BF%E5%85%AC%E5%85%B1%E5%AD%90%E5%BA%8F%E5%88%97

**Comment by liyongsea** [comment]
- 数据准备好给thomas翻译

**Comment by liyongsea** [comment]
https://gist.github.com/Wzixiao/53f6b3948dba4fcf657008058041cf97 -> 青禾测试
