### ISSUE TITLE
[UN corpus] 下载联合国digital library的pdf并且转化成文本格式上传huggingface

### ISSUE THREAD

**Issue by liyongsea** [liyongsea/parallel_corpus_mnbvc#4]
https://digitallibrary.un.org/?ln=en 目前包含
- 约400G的pdf
- 共？？多余种的文档
- 20个6语言的官方文档

目标是下载所有的文档并转成文本格式，上传huggingface

# Update 0413 - download data after 2000
- we realize some pdf might contain image, to simplify the task, we now focus on pdf before year 2000

**method**
- get all url from sitemap, crown the pdf date from the website (need to run ~12h. where is the code ?)
- crown pdf according to their date

**related data**
- 3 millions urls (html) available on https://digitallibrary.un.org/?ln=en
- 223K documents (correspond to 7x223K urls in the sitemap) with 6 official languages of UN (we call it parallel url)
- 146K after 2000 AC (could be converted easily into text)
- ?? analytics on the converted text

**Comment by liyongsea** [comment]
- 已下载50% - 220G （40小时 ）wangran
- 66万六国语言
- 先忽略阿拉伯语言
- 17小时转了一半，30%能直接转文档（liyongsea），pr转码的代码

**Comment by Wzixiao** [comment]
> 根据时间排序完毕的链接获取地址 "https://huggingface.co/datasets/ranWang/un_pdf_record_list_set"

**Comment by liyongsea** [comment]
pdf to text script is missing

**Comment by liyongsea** [comment]
- 做一个年代文件数的histogramme
- 看一下2000年以前的文档有没有能用的

**Comment by Wzixiao** [comment]
新的数据源:https://documents.un.org
