### ISSUE TITLE
[UN corpus] 下载联合国documents(doc)

### ISSUE THREAD

**Issue by Wzixiao** [liyongsea/parallel_corpus_mnbvc#48]
https://documents.un.org/

**Comment by liyongsea** [comment]
- 完成爬虫代码，爬文件地址（xec）
- 下载doc（拿取cookie）
- 从doc提取文本
- 对齐

**Comment by liyongsea** [comment]
完成文件地址爬取 https://huggingface.co/datasets/dabaisuv/UN_Documents_2000_2023

**Comment by liyongsea** [comment]
@Wzixiao 看一下代码

**Comment by liyongsea** [comment]
https://gist.github.com/Wzixiao/53f6b3948dba4fcf657008058041cf97 -> 青禾测试

**Comment by liyongsea** [comment]
文件压缩包我上传到百度云了

链接：https://pan.baidu.com/s/1fgQ05rP7Bn_la6Fvz1ipEg?pwd=al2r 
提取码：al2r 
--来自百度网盘超级会员V4的分享
